name: Daily Data Update

on:
  schedule:
    - cron: "0 6 * * *"   # runs every day at 6:00 AM UTC (adjust later if needed)
  workflow_dispatch:       # allows manual run from GitHub Actions tab

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pandas faker matplotlib prophet

      - name: Run data generator
        run: python generate_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add grocer_ai_data.csv
          git commit -m "chore: auto-update data"
          git push

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Grocer-AI Data Updated ✅"
          to: your_email@gmail.com
          from: Grocer-AI Bot <your_email@gmail.com>
          body: "The dataset has been updated and pushed to GitHub."
