[theme]
primaryColor = "#4CAF50"          # Green
backgroundColor = "#F5F5F5"       # Light gray
secondaryBackgroundColor = "#FFFFFF" # White
textColor = "#000000"             # Black
font = "sans serif"
